#domain.name=test-web.com
#server.port=80
###mysql
#jdbc.driverClass=com.mysql.jdbc.Driver
#jdbc.jdbcUrl=jdbc:MySql://192.168.8.240:3306/test?characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false
#jdbc.username=dev
#jdbc.password=111111
#jdbc.filters=slf4j
#jdbc.maxActive=20
#jdbc.initialSize=1
#jdbc.maxWait=60000
#jdbc.minIdle=10

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jjdbc:MySql://localhost:3306/test?characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: root
    password: 9999
    type: com.alibaba.druid.pool.DruidDataSource

##redis
#redis.ip=192.168.8.241
#redis.port=6379
#redis.defaultExpireTime = 1800
#redis.useCache=true

log.level: info
project.build.sourceEncoding=UTF-8


