
CREATE TABLE `user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`name` VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
	`password` VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
	`age` SMALLINT(6) NULL DEFAULT NULL COMMENT '年龄',
	`creator` BIGINT(20) NULL DEFAULT NULL COMMENT '创建人',
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	`yn` INT(11) NOT NULL DEFAULT '1' COMMENT '是否可用',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

